### ISSUE TITLE
Magic request methods require a URI and optional options array

### ISSUE THREAD

**Issue by mostafasoufi** [twizoapi/lib-api-php#1]
Hi Guys,
I've using the Twizo example codes for sending message but I getting following exception error in the first step:

`Magic request methods require a URI and optional options array`

It's seems this error already in [Guzzle library](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L81).
I think the example code should be update.

**Comment by cobaltjeh** [comment]
Hi Mostafa,

Which version/branch of Guzzle are you using in you project?
I can re-produce the error using the latest dev-master of Guzzle package. 

Our package however limits installation of Guzzle package in 5.3 branch.
Have you included our package using composer? As our package constraints should normally not allow the dev-master of Guzzle to be installed.

**Comment by mostafasoufi** [comment]
Yes, i using your package with composer and the latest version of guzzle installed.

**Comment by Bersman** [comment]
Which version of composer do you use?

**Comment by mostafasoufi** [comment]
Solved! included two package of guzzle in the project.

**Comment by nirmalgoswami** [comment]
Please provide your solution. which package did you included ?

**Comment by emiel-silverstreet** [comment]
In the newest version (currently 0.10.0) there is no longer a dependency on Guzzle. Please update to resolve the problem with Guzzle.
If you experience any other problems with the package, please let us know by creating a new issue.

**Comment by dsvvimal** [comment]
Hi,
I am also running with the same issue "Magic request methods require a URI and optional options array",
Kindly suggest me how to solve this issue

**Comment by vincentkollebolle** [comment]
up !

**Comment by emiel-silverstreet** [comment]
@vincentkollebolle As indicated on December 14th, the Twizo Api library no longer uses Guzzle in the latest version. If you have any other issues with the latest version of the Twizo Api library, you are welcome to open a new issue for this.
