### ISSUE TITLE
Magic request methods require a URI and optional options array

### ISSUE THREAD

**Issue by dsvvimal** [twizoapi/lib-api-php#3]
Hi, I am experiencing the below error when using $client->getHttpClient()->setDefaultOption('verify', false)
"Magic request methods require a URI and optional options array" , could you please help me in solving this issue. let me know if i need to update the package

**Comment by emiel-silverstreet** [comment]
Which version are you using?
Are you experiencing this issue when using the latest version of the package? If so, can you give a code example?

**Comment by dsvvimal** [comment]
Hi,
I am using guzzle 6.0. below is my code
$https = $client->getHttpClient()->setDefaultOption('verify', 'C:/xampp/php/extras/ssl/cacert.pem');
			
		$client->setHttpClient($https);
				
		$request = new \GuzzleHttp\Psr7\Request('GET', 'https://services.groupkt.com/state/get/IND/all');
		$promise = $client->sendAsync($request)->then(function ($response) {
		    echo  $response->getBody();
		});

**Comment by emiel-silverstreet** [comment]
Which version of the Twizo PHP library are you using? Which function of the Twizo API are you trying to use?

**Comment by dsvvimal** [comment]
I am not using  Twizo PHP library

**Comment by dsvvimal** [comment]
do i need to update any package in guzzle?

**Comment by emiel-silverstreet** [comment]
You have created this issue in the Twizo PHP library project; this is only intended for issues related to the Twizo PHP library. For issues about Guzzle, please use the [Guzzle issue tracker](https://github.com/guzzle/guzzle/issues).

**Comment by dsvvimal** [comment]
I am very sorry for this. Thanks
